### ISSUE TITLE
references to 'cv :: SURF :: SURF ()' undefined

### ISSUE THREAD

**Issue by DaxiongAI** [apennisi/rgbd_person_tracking#1]
In the function 'tracker :: Tracker :: track (std :: vector <tracker :: detection_struct, std :: allocator <tracker :: detection_struct>> const &, cv :: Mat const &)'
/home/daxiong/ros_study_ws/src/rgbd_person_tracking-master/visual_tracker/src/Tracker.cpp:78: references to 'cv :: SURF :: SURF ()' undefined

**Comment by apennisi** [comment]
You have to install on your laptop the nonfree package of opencv. 
For Ubuntu:

```
sudo add-apt-repository --yes ppa:xqms/opencv-nonfree
sudo apt-get update 
sudo apt-get install libopencv-nonfree-dev
```

**Comment by DaxiongAI** [comment]
it's ok,Thank you for your answer

**Comment by apennisi** [comment]
You are welcome!

**Comment by Luna2199** [comment]
I also need to add "geometry_msgs"in CMakeList.txt, and package.xml.
