### ISSUE TITLE
Fatal Error:people_msgs/**.h:No such file or directory

### ISSUE THREAD

**Issue by Luna2199** [apennisi/rgbd_person_tracking#2]
Excuse me, sir! 
      When I command "catkin_make" in catkin_ws workspace, then it got some wrong, such as, "/home/boocax/catkin_ws/src/visual_tracker/src/main.cpp:34:40: fatal error: people_msgs/SegmentedImage.h: No such file or directory", "/home/boy/catkin_ws/src/ground_detector/src/blob_extraction.h:43:34: fatal error: people_msgs/Clusters.h: No such file or directory", 
      what's wrong about it? How can I do with those problem? Help me, please....
Ubuntu14.05, Indigo Ros, PCL 1.7, OpenCV 2.4.8, Boost 1.58

**Comment by apennisi** [comment]
Try to compile the program more times until everything works well. Unfortunately, sometimes ROS does not compile the messages when you launch "catkin_make" for the first time. Launch it many times.

**Comment by Luna2199** [comment]
That's OK, Thank you。I already solve it .
