### ISSUE TITLE
OpenCV problem while running people detector node.

### ISSUE THREAD

**Issue by iabhisharma** [apennisi/rgbd_person_tracking#3]
The ground detector node and dispatcher node work fine and are giving output on their  respective topics But when I run people_detector_node it fails with the following kind of errors -
1. OpenCV Error: The function/feature is not implemented (Unknown/unsupported array type) in create, file /home/abhsihek/libs/opencv/modules/core/src/matrix.cpp, line 2842
[ERROR] [1500641324.950684392]: PROBLEM WITH THE DETECTOR!
2. OpenCV Error: Assertion failed (!_mv.fixedType() || _mv.empty() || _mv.type() == m.depth()) in split, file /home/abhsihek/libs/opencv/modules/core/src/convert.cpp, line 262
[ERROR] [1500642358.248942443]: PROBLEM WITH THE DETECTOR!
3. OpenCV Error: Assertion failed (mtype == type0 || (CV_MAT_CN(mtype) == CV_MAT_CN(type0) && ((1 << type0) & fixedDepthMask) != 0)) in create, file /home/abhsihek/libs/opencv/modules/core/src/matrix.cpp, line 2599
[ERROR] [1500642367.533972948]: PROBLEM WITH THE DETECTOR!

So whenever I run people_detector_node I get an error from the 3 mentioned ones. 
Can you help me with the problem ? Any kind of help is appreciated.
Thank you.

**Comment by apennisi** [comment]
Are you using the same version of opencv that I used and also ROS indgo? It is related to opencv.

**Comment by iabhisharma** [comment]
Actually I am using ROS kinetic (Ubuntu 16.04) and the OpenCV bundled with it. I have tried few generic solution for OpenCV but it seems nothing works for me. 
I am using Kinect V2 for my RGBD data. Could that cause some issue ? I was able to run the ground_detector and dispatcher_node so I assumed that my settings and input RGBD data was correct.

**Comment by apennisi** [comment]
The problem I think is the version of opencv. No, the sensor is not important, I did not test with kinetic. Is the version of opencv the number 3? Did you try to use gdb to understand where the error is in the code?

**Comment by iabhisharma** [comment]
Yes I have opencv version 3 installed on my system but in the cmakelist file I am looking for the same version of opencv as you. I know at which line of the code it throws an error -
This is the part of the code where it throws the error -
filename - people_detection_node.cpp
Line number - from 96 - 98
Code -     cv::resize(image,resized,cv::Size(image.cols/_imageScalingFactor,image.rows/_imageScalingFactor));
detector->process(image);
bboxes = detector->getBBoxes();

I have checked that the image is not empty and I am confused because opencv doesn't throw the same error always. It gives a new error every time.

**Comment by apennisi** [comment]
I did not tested it with Opencv 3 and kinetic, the problem is also the tracker which works  only with opencv 2. On Monday I try at least the person detector node with kinetic and opencv 3.
If in the meanwhile you solve the problem, let me know.

**Comment by iabhisharma** [comment]
Yes I will be working on this over the weekend and if I get it to work I will update this thread.
Thank you.
