### ISSUE TITLE
Detection is working but no tracking

### ISSUE THREAD

**Issue by Kapcirt** [apennisi/rgbd_person_tracking#4]
Hello, 
I managed to make the detection work but there is never any tracking. The clusters in every ROS topics are empty.

The input ROS topics are the camera info (roof_rgbd_camera/depth/camera_info), the rgb image (roof_rgbd_camera/rgb/image_raw) with a resolution of 240*320 and the depth image (roof_rgbd_camera/depth/image_rect) with a resolution of 240*320 and the depth in meter.

Do you know what might be happening ?

Thank you

**Comment by apennisi** [comment]
Hello,

Sorry, but I cannot know what you do. Anyway, it takes as input images of 640x480.
Maybe, it could be the reason.

Best,
Andrea
