### ISSUE TITLE
How to explain the method GroundDetection::process() ?

### ISSUE THREAD

**Issue by cggos** [apennisi/rgbd_person_tracking#5]
How to explain the method GroundDetection::process()  linking to https://github.com/apennisi/rgbd_person_tracking/blob/master/ground_detector/src/ground_detection.cpp#L82-L112 ? Is there any document about it ? Thank you.

**Comment by apennisi** [comment]
Have a look at this: http://research.sabanciuniv.edu/33937/1/PID4962853.pdf
