### ISSUE TITLE
AlgorithmInfo Issue

### ISSUE THREAD

**Issue by varsha-devi** [apennisi/rgbd_person_tracking#7]
When I am compiling the project using catkin_make inside the cakin workspace I am facing this error I dont know y???

![screenshot from 2019-02-28 10-41-45](https://user-images.githubusercontent.com/45758791/53557108-7e582980-3b45-11e9-8cf4-8e71e9077f8a.png)

**Comment by apennisi** [comment]
I think you are using a version of opencv not compatible with my stuff. Anyway, this is the first link I found by googling it: [https://stackoverflow.com/questions/29750303/opencv-algorithminfo-does-not-name-a-type-while-building-opencv-contrib](error). 
I suggest you to read the error, understand if it is something related to some library and then trying to google it.
